package com.template.models

data class LoginData(
    var __v: Int? = null,
    var _id: String? = null,
    var address: String? = null,
    var createdAt: String? = null,
    var deviceType: String? = null,
    var email: String? = null,
    var expire: Int? = null,
    var firstName: String? = null,
    var image: String? = null,
    var isBlocked: Boolean? = null,
    var isDeleted: Boolean? = null,
    var isEmailVerify: Boolean? = null,
    var isPhoneVerify: Boolean? = null,
    var isProfileComplete: Boolean? = null,
    var jwtCreatedAt: Int? = null,
    var lastName: String? = null,
    var latitude: Int? = null,
    var longitude: Int? = null,
    var phone: String? = null,
    var postCode: String? = null,
    var refreshToken: String? = null,
    var token: String? = null,
    var type: String? = null,
    var updatedAt: String? = null,
    var userName: String? = null,
    var verificationType: Int? = null
)